Fix unstable test TestRetryJoin in travis
As seen in https://travis-ci.org/hashicorp/consul/jobs/551065657

Try solving this issue that cause failures and delays while testing in travis:

--- FAIL: TestRetryJoin (7.26s)
    retry.go:121: agent_test.go:125: got 1 LAN members want 2