Fix TestManager_BasicLifecycle to have less issues in travis
As seen in https://travis-ci.org/hashicorp/consul/jobs/551056889

The test fails quite often on Travis due to poor performance:

```
--- FAIL: TestManager_BasicLifecycle (1.33s)
    manager_test.go:179: recv timeout
FAIL
```

This PR increase timeout to avoid this test to restart the whole testing.

This should speed up tests and increase reliability